/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_test_custom_mydemos_NDK_L6_JniTest */

#ifndef _Included_com_test_custom_mydemos_NDK_L6_JniTest
#define _Included_com_test_custom_mydemos_NDK_L6_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_test_custom_mydemos_NDK_L6_JniTest
 * Method:    getCFromJni
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_test_custom_mydemos_NDK_L6_JniTest_getCFromJni
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
