/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_test_custom_mydemos_NDK_L6_L6 */

#ifndef _Included_com_test_custom_mydemos_NDK_L6_L6
#define _Included_com_test_custom_mydemos_NDK_L6_L6
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_test_custom_mydemos_NDK_L6_L6
 * Method:    testMyC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_test_custom_mydemos_NDK_L6_L6_testMyC
  (JNIEnv *, jclass);

/*
 * Class:     com_test_custom_mydemos_NDK_L6_L6
 * Method:    testC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_test_custom_mydemos_NDK_L6_L6_testC
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
