/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_test_custom_mydemos_NDK_L6_MyJni */

#ifndef _Included_com_test_custom_mydemos_NDK_L6_MyJni
#define _Included_com_test_custom_mydemos_NDK_L6_MyJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_test_custom_mydemos_NDK_L6_MyJni
 * Method:    getMyC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_test_custom_mydemos_NDK_L6_MyJni_getMyC
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
